config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  root    'users#new'

  resources :users

  get 'places/' =>          'places#index'
  
  post   'places/' =>       'places#create'

  get   'places/new' =>     'places#new', as: :new_place

  get   'places/:id/edit' =>'places#edit', as: :edit_place

  get 'places/:id' =>       'places#show', as: :place

  patch 'places/:id'  =>    'places#update'

  delete 'places/:id' =>    'places#destroy'

end

app/models/place.rb
class Place
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :photo, type: String
  field :notes, type: String

  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  validates :name, presence: true

  validates :email, format: { with: /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/, message: "Invalid email format." }

  has_many :places

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :set_cache_buster
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.where(id: session[:user_id]).first
  end

  # don't allow rails page caching so google maps loading doesn't break
  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		if !current_user 
			redirect_to root_path
		else
			@places = current_user.places.all
		end
	end

	def new
		@place = Place.new
	end

	def show
		@place = Place.find(params[:id])
	end

	def create
		@place = current_user.places.new(places_params)
		if @place.save
			redirect_to places_path
		else
			render :new
		end
	end

	def edit
		@place = Place.find(params[:id])
	end

	def update
		@place = Place.find(params[:id])
		if @place.update_attributes(places_params)
			redirect_to places_path
		else
			render 'edit'
		end
	end

	def destroy
		@place = Place.find(params[:id])
		@place.destroy
	    redirect_to places_path
	end

private
	def places_params
		params.require(:place).permit(:name, :address, :photo, :notes)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in    
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to places_path
		else
			# Go back to the login page
			redirect_to root_path
		end
	end

	def destroy
		reset_session
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :check_user_logged_in, only: [:edit, :update, :destroy]

	def index
		if current_user 
			redirect_to places_path
		end
		@users = User.all
		@places = Place.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
		@is_login = true
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			render :new
		end
	end

	private

    def check_user_logged_in
		if !current_user
			redirect_to root_path
		end
    end

	def user_params
    	params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food Grab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>

  <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwxiOWzN5SQpc4_85EiSTpAZxJFfMe9uE">
</script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<div class="row-fluid pull-right">
		<div class="login-shiv">
			<% if current_user %>
				Welcome, <%= current_user.name %> --
				<%= link_to "Log out", session_path, method: :delete, class: "btn btn-success" %>
			<% end %>
		</div>
	</div>

	<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="container">
	<div id="form-container">
	<%= form_for @place do |f| %>
		
		<% if @place.errors.any? %>
			<ul>
				<% @place.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

		<div class="field form-group">
			<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
		</div>
		<div class="field form-group">
			<%= f.text_field :address, placeholder: "Address", class: "form-control" %>
		</div>

		<div class="field form-group">
			<%= f.text_field :notes, placeholder: "Notes", class: "form-control" %>
		</div>
		<div class="actions">
			<%= f.submit "Submit", class: "btn btn-default" %>
		</div>
	<% end %>
	<p>&nbsp;</p>
	<a class="btn btn-success" href="javascript:window.history.back()">Go Back</a>
</div>
</div>

app/views/places/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 title">Food Grab</div>
		<div class="col-md-4"></div>
	</div>

	<br />
	<div class="row" style="height: 600px">
		<div class="col-md-6" style="height: 100%">
			<div id="map"></div>
		</div>
		<div class="col-md-6">
			
			<div class="row">
				<%= link_to "Add a place", new_place_path, class: "btn-lg btn-success place-button" %>
			</div>

			<div class="row">&nbsp;</div>

			<% @count = 0 %>

			<div class="row">
				<ul>
					<% if @places.empty? %>
						<h3>You currently don't have any favorite places to eat saved. Click the "Add A Place" button to save a place.</h3>
					<% else %>
						<% @places.each do |p| %>
							<li class="places">
								<span class="name<%= @count %> place-name"><%= p.name %></span> 
								<span class="pull-right admin">
									<%= link_to 'Edit', edit_place_path(p), class: "btn-sm btn-info" %>
									<%= link_to "Delete", 'places/' + p.id, method: :delete, class: "btn-sm btn-danger" %>
								</span>
								<br />
								<p><strong>Address:</strong> <span class="address<%= @count %>"><%= p.address %></span></p>
								<p><strong>Notes:</strong> <span class="notes<%= @count %>"><%= p.notes %></span></p>
							</li>
							<% @count = @count + 1 %>
						<% end %>
					<% end %>
				</ul>
			</div>

		</div>
	</div>
</div>

app/views/places/new.html.erb
<div class="container">
	<h1>Add a place</h1>
	<div id="form-container">

		<%= form_for @place do |p| %>
			
			<% if @place.errors.any? %>
				<ul>
					<% @place.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			<% end %>

			<div class="field form-group">
				<%= p.text_field :name, placeholder: "Name of place", class: "form-control" %><br />
			</div>
			<div class="field form-group">
				Example: 225 Santa Monica Blvd, Santa Monica, CA 90401
				<%= p.text_field :address, placeholder: "Address of place", class: "form-control" %><br />
			</div>

			<div class="field form-group">
				<%= p.text_field :notes, placeholder: "Notes...", class: "form-control" %><br />
			</div>
			<div class="actions">
				<%= p.submit "Submit", class: "btn btn-default" %>
			</div>
		<% end %>
		<p>&nbsp;</p>
		<a class="btn btn-success" href="javascript:window.history.back()">Go Back</a>

	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 title">Food Grab</div>
		<div class="col-md-4"></div>
	</div>

	<!-- required to avoid javascript errors from places.js -->
	<div id="map" style="display:none"></div>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-3 text-center">
			<h2 class="subtitle">Never forget where to eat again</h2>
			<p>We all forget some of the tasty places we have discovered to eat. 
				Allow Food Grab to save your favorite places for you on a Google Map.</p>
			<a id="signup-menu" class="btn btn-primary" href="#sidr-signup">Sign Up</a> | 
			<a id="login-menu" class="btn btn-success" href="#sidr-login">Log In</a>
		</div>
		<div class="col-md-3 map-background">
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

<div id="sidr-signup">
	<div id="signup-form">
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<ul>
        			<% @user.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
        			<% end %>
    			</ul>
			<% end %>
			<%= f.text_field :name, placeholder: "Name" %><br />
			<%= f.text_field :email, placeholder: "Email" %><br />
			<%= f.password_field :password, placeholder: "Password" %><br />
			<%= f.submit "Submit" %>
		<% end %>
	</div>
</div>

<div id="sidr-login">
	<div id="login-form">
		<%= form_for @user, {url: session_path} do |f| %>
			<% if @user.errors.any? %>
				<ul>
        			<% @user.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
        			<% end %>
    			</ul>
			<% end %>
			<%= f.text_field :email, placeholder: "your email address.." %><br />
			<%= f.password_field :password, placeholder: "password ..." %><br />
			<%= f.submit "Log In" %>
		<% end %>
	</div>
</div>